bdp-platform:
  sys-code: bdp-datasource
spring:
  application:
    name: bdp-datasource
security:
  oauth2:
    client:
      clientId: bdp
      clientSecret: bdp
      user-authorization-uri: http://127.0.0.1:8080/oauth/authorize
      access-token-uri: http://127.0.0.1:8080/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:8080/oauth/token_key