server:
  port: 8762
logging:
  level:
    tk.mybatis: DEBUG
    com.bdp.framework: DEBUG
bdp-platform:
  sys-code: framework
  proxy-mapping: 
spring:
  application:
    name: bdp-framework
  datasource:
    name: bdp_db
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bdp_db?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root