server:
  port: 8762
logging:
  level:
    tk.mybatis: DEBUG
    com.bdp.framework: DEBUG
framework:
  busiSysCode: framework
spring:
  application:
    name: bdp-framework
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    suffix: .html
    remark: html文件关联到xml编辑器,那样格式化比较漂亮,eclipse html编辑器对自定义标签不认，格化式太差,
    remark2: mode设置为LEGACYHTML5主要是为了使用thymeleaf兼容element-ui等自定义标签,否则解析报错。
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  datasource:
    name: bdp_db
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bdp_db?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  basepackage: com.bdp.**.mapper
  xmlLocation: classpath:mapper/**/*.xml