framework:
  busiSysCode: bdp-config
server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/info
  client:
    service-url.defaultZone: http://localhost:8081/eureka
spring:
  application:
    name: bdp-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: configs,./configs
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    suffix: .tml
    remark: suffix后缀改为.tml主要是为了把.tml文件关联到xml编辑器,那样格式化比较漂亮,mode设置为LEGACYHTML5主要是为了兼容element-ui等自定义标签
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  datasource:
    name: bdp_db
    url: jdbc:mysql://localhost:3306/bdp_db?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  basepackage: com.bdp.*.mapper
  xmlLocation: classpath:mapper/**/*.xml